steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'kwelo'
    entrypoint: 'sh'
    dir: './app'
    args:
      - '-c'
      - |
         apt-get update && apt-get upgrade -y && \
         apt-get install apt-utils -y && \
         apt-get install sqlite3 -y;
         apt-get install python3-pip -y && \
         pip install flask && \
         pip freeze > requirements.txt && \
         pip install --no-cache-dir -r requirements.txt 
         python3 ./demo.py

timeout: "1600s"